eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123
    url: jdbc:mysql://127.0.0.1/jpa_new?serverTimezone=UTC&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
  jpa:
    show-sql: true
  rabbitmq:
    host: 159.203.12.180
    port: 5672
    username: guest
    password: guest
  redis:
    host: localhost
    port: 6379
