spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123
    url: jdbc:mysql://159.203.13.39/jpa_new?serverTimezone=UTC&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: ming
  jpa:
    show-sql: true
  #rabbitmq:
  #  host: 159.203.12.180
  #  port: 5672
  #  username: guest
  #  password: guest
  redis:
    host: localhost
    port: 6379
